services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"   # RabbitMQ message broker port
      - "15672:15672" # RabbitMQ management UI
      
  userprofileservice:
    image: userprofileservice
    build:
      context: .
      dockerfile: UserProfileService/Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      - rabbitmq

  tweetpostingservice:
    image: tweetpostingservice
    build:
      context: .
      dockerfile: TweetPostingService/Dockerfile
    ports:
      - "5002:80"
    depends_on:
      - userprofileservice

  interactionservice:
    image: interactionservice
    build:
      context: .
      dockerfile: InteractionService/Dockerfile
    ports:
      - "5003:80"
    depends_on:
      - tweetpostingservice
      - userprofileservice
  
  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    ports:
      - "5020:80"
    depends_on:
      - userprofileservice
      - tweetpostingservice
      - interactionservice

  # Adding Seq for logging
  seq:
    image: datalust/seq:latest
    ports:
      - 5341:5341 # Exposing Seq on localhost:534
      - 5342:80 # Exposing Seq on localhost:5341
    environment:
      ACCEPT_EULA: Y
    volumes:
      - seq-data:/data

  # Adding Zipkin for tracing
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411 # Exposing Zipkin on localhost:9411
        


volumes: 
  seq-data: