services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"   # RabbitMQ message broker port
      - "15672:15672" # RabbitMQ management UI
  userprofileservice:
    image: userprofileservice
    build:
      context: .
      dockerfile: UserProfileService/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - rabbitmq

  tweetpostingservice:
    image: tweetpostingservice
    build:
      context: .
      dockerfile: TweetPostingService/Dockerfile
    ports:
      - "5002:80"
    depends_on:
      - userprofileservice

  interactionservice:
    image: interactionservice
    build:
      context: .
      dockerfile: InteractionService/Dockerfile
    ports:
      - "5003:80"
    depends_on:
      - tweetpostingservice
      - userprofileservice
  
  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - userprofileservice
      - tweetpostingservice
      - interactionservice
