services:
  
  userprofile-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: false
    volumes:
      - mssql-data-userprofiles:/var/opt/mssql
  
  
  
  userprofileservice:
    image: userprofileservice
    build:
      context: .
      dockerfile: UserProfileService/Dockerfile
    depends_on:
      - userprofile-db

  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    ports:
      - "5020:80"
    depends_on:
      - userprofileservice
      - userprofile-db

  # Adding Seq for logging
  seq:
    image: datalust/seq:latest
    ports:
      - 5341:5341 # Exposing Seq on localhost:534
      - 5342:80 # Exposing Seq on localhost:5341
    environment:
      ACCEPT_EULA: Y
    volumes:
      - seq-data:/data

  # Adding Zipkin for tracing
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411 # Exposing Zipkin on localhost:9411
        


volumes: 
  seq-data:
  mssql-data-userprofiles: