services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"   # RabbitMQ message broker port
      - "15672:15672" # RabbitMQ management UI

  userprofileservice:
    image: userprofileservice
    build:
      context: .
      dockerfile: UserProfileService/Dockerfile
    depends_on:
      - rabbitmq
    deploy:
      replicas: 2  # Two replicas for x-axis scaling
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
      restart_policy:
        condition: on-failure

  tweetpostingservice:
    image: tweetpostingservice
    build:
      context: .
      dockerfile: TweetPostingService/Dockerfile
    depends_on:
      - userprofileservice
    deploy:
      replicas: 2  # Two replicas for x-axis scaling
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
      restart_policy:
        condition: on-failure

  interactionservice:
    image: interactionservice
    build:
      context: .
      dockerfile: InteractionService/Dockerfile
    deploy:
      replicas: 2  # Two replicas for x-axis scaling
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
      restart_policy:
        condition: on-failure

  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    ports:
      - "5001:8080"
    deploy:
      # replicas: 2  # Two replicas for x-axis scaling
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
      restart_policy:
        condition: on-failure
