---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apigateway-sa
  namespace: default

---

apiVersion: v1
kind: Service
metadata:
  name: apigateway
  labels:
    app: apigateway
spec:
  selector:
    app: apigateway
  ports:
    - protocol: TCP
      port: 80         # External clients access the service on port 80
      targetPort: 8080 # Forwards traffic to container's port 8080
      nodePort: 5001   # Specific NodePort for external access
  type: NodePort         # Exposes the service via the NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  labels:
    app: apigateway
spec:
  replicas: 3  # Ensures high availability with 3 instances
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      serviceAccountName: apigateway-sa   # Use the  defined ServiceAccount
      containers:
        - name: apigateway
          image: socialnetworkapp/apigateway
          imagePullPolicy: Never
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: apigateway-allow-specific-traffic
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: apigateway
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: # Allow traffic only from the following services
            matchLabels:
              app: userprofileservice
        - podSelector:
            matchLabels:
              app: tweetpostingservice
        - podSelector:
            matchLabels:
              app: interactionservice
