apiVersion: v1
kind: Service
metadata:
  name: interactionservice
  labels:
    app: interactionservice
spec:
  selector:
    app: interactionservice
  ports:
    - protocol: TCP
      port: 8080         # Service is exposed on port 80
      targetPort: 8080 # Forwards traffic to container's port 8082
  type: ClusterIP       # Internal access only; use LoadBalancer for external access

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: interactionservice
  labels:
    app: interactionservice
spec:
  replicas: 3  # Ensures high availability with 3 instances
  selector:
    matchLabels:
      app: interactionservice
  template:
    metadata:
      labels:
        app: interactionservice
    spec:
      containers:
        - name: interactionservice
          image: socialnetworkapp/interactionservice  
          imagePullPolicy: Never
          env:  # Add environment variables if needed
